remote_theme: pages-themes/merlot@v0.2.0
plugins:
  - jekyll-remote-theme # Ensure you include this plugin
  - jekyll-feed
title: My AI Journey Blog
description: Sharing my journey with AI and learning
github_username: katprincess
markdown: kramdown
paginate: 5
